version: '2'

services:
  database:
    env_file:
      - .env
    build:
      context: database
      args:
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        - MARIADB_DATABASE=${MARIADB_DATABASE}
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      dockerfile: Dockerfile
    container_name: message-board-database
    ports:
      - ${LOCAL_DB_PORT}:${VIRTUAL_DB_PORT}
    restart: always
    networks:
      obscenity:
        ipv4_address: 172.21.0.2
  server:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_HOST=database
    container_name: message-board-server
    ports:
      - ${LOCAL_SERVER_PORT}:${VIRTUAL_SERVER_PORT}
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
    networks:
      obscenity:
        ipv4_address: 172.21.0.3
networks:
  obscenity:
    ipam:
      config:
        - subnet: 172.21.0.0/16